# Generated by Django 4.2.2 on 2023-06-24 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категорії',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва')),
                ('ingredients', models.CharField(max_length=255, verbose_name='Інгредієнти')),
                ('description', models.TextField(null=True)),
                ('photo', models.ImageField(upload_to='pizzas', verbose_name='Фото')),
                ('price', models.CharField(max_length=100, verbose_name='Ціна')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pizza.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Піцу',
                'verbose_name_plural': 'Піца',
                'ordering': ['-time_create'],
            },
        ),
    ]
